#!/bin/bash

MINISHELL=./minishell
COMMANDS=(
	# "echo hi"
	# "echo hi bye"
	# "echo"
	# "echo \"\""
	# "echo \"hi\""
	# "echo 'hi'"
	# "echo 'hi'bye"
	# "echo hi'bye'"
	# "echo \"hi\"bye"
	# "echo hi\"bye\""
	# "echo \"'hi'\""
	# "echo hi'bye'hi\"bye\""
	# "echo \"\"\"\""
	"echo ''''"
	"echo \"'\"'\"'"
	"echo hi > out"
	"echo hi < in > out"
	"echo hi<in > out"
	"echo hi<in>out"
	"echo hi >> out"
	"echo hi>>out"
	"echo \"hi\" > out"
	"echo 'hi' > out"
	"echo \"hi\" < in"
	"echo \"hi\">\"out\""
	"echo 'hi'>'out'"
	# "cat < \"in\" > \"out\""
	# "cat <'in'>'out'"
	# "echo \"hi > out\""
	# "echo 'hi < in'"
	# "echo \"hi\" >> \"out\""
	# "echo hi | bye"
	# "echo hi|bye"
	# "echo hi | cat"
	# "echo hi | cat | grep h"
	# "echo hi|cat|grep h"
	# "ls | grep test | wc -l"
	# "cat file | sort | uniq"
	# "echo hi | cat > out"
	# "cat < in | grep h"
	# "cat < in | grep h > out"
	# "echo hi > out | cat"
	# "cat < in | grep h | wc > out"
	# "echo hi|cat<in>out"
	# "cat<in|grep h>out|wc"
	# "echo hi>out|bye"
	# "echo hi<in>out|bye"
	# "echo \"hi\" | cat"
	# "echo 'hi' | cat"
	# "echo \"hi | cat\""
	# "echo 'hi | cat'"
	# "echo \"hi\"|cat|grep \"h\""
	# "echo 'hi'|cat|grep 'h'"
	# "cat \"file\" | grep 'pattern'"
	# "echo \"hi\" | cat > \"out\""
	# "cat < \"in\" | grep \"h\" > \"out\""
	# "echo 'hi'|cat<'in'>'out'"
	# "cat \"file\" | grep 'pattern' > output"
	# "echo \"test\" < 'in' | cat > \"out\""
	# "cat<\"in\"|grep 'h'|wc>'out'"
	# ""
	# "   "
	# "\t"
	# "\t\t\t"
	# "  \t  \t  "
	# "echo    hi    bye"
	# "echo\thi"
	# "echo  \t  hi  \t  bye"
	# "  echo hi  "
	# "\techo hi\t"
	# "  \t  echo  \t  hi  \t  "
	# "echo   >   out"
	# "echo\t>\tout"
	# "echo  \t  >  \t  out"
	# "echo   |   cat"
	# "echo\t|\tcat"
	# "echo  \t  |  \t  cat"
	# "echo   <   in   >   out"
	# "echo\t<\tin\t>\tout"
	# "cat << EOF"
	# "cat <<EOF"
	# "cat << \"EOF\""
	# "cat <<'EOF'"
	# "echo $USER"
	# "echo \"$USER\""
	# "echo '$USER'"
	# "echo hi;bye"
	# "echo \"hi"
	# "echo 'hi"
	# "echo \"hi'"
	# "echo 'hi\""
	# "echo \"hello world"
	# "echo 'hello world"
	# "cat \"file"
	# "cat 'file"
	# "echo >"
	# "echo <"
	# "echo < "
	# "echo > "
	# "echo >>"
	# "echo <<"
	# "echo > < out"
	# "echo < > in"
	# "echo hi ><out"
	# "echo hi <>out"
	# "echo hi >><<out"
	# "echo hi>>>out"
	# "echo hi< <<in"
	# "echo hi> >>out"
	# "echo hi< <<in"
	# "echo hi>> >out"
	# "echo hi<< <in"
	# "echo hi>>> out"
	# "echo hi<<< in"
	# "|"
	# "||"
	# "|| "
	# "| |"
	# " | | | "
	# "|||"
	# "echo |"
	# "echo | | cat"
	# "echo ||"
	# "echo |||"
	# "echo hi |"
	# "echo | | cat"
	# "echo hi | | cat"
	# "echo hi|| |bye"
	# "echo hi|||bye"
	# "echo hi||| bye"
	# "echo hi||| bye"
	# "echo \"hi | cat"
	# "echo 'hi > out"
	# "echo \"hi\" | "
)

for cmd in "${COMMANDS[@]}"; do
    echo -e -n "$cmd\t"

    # Run minishell
    MINI_OUT=$($MINISHELL -c "$cmd" 2>&1)
    MINI_STATUS=$?

    # Run bash
    BASH_OUT=$(bash -c "$cmd" 2>&1)
    BASH_STATUS=$?

    # Compare results
    if [[ "$MINI_OUT" == "$BASH_OUT" && "$MINI_STATUS" == "$BASH_STATUS" ]]; then
        echo -e "\033[32mOK\033[0m"
    else
        echo -e "\033[31mKO\033[0m"
        echo "minishell output : [$MINI_OUT]"
        echo "bash output      : [$BASH_OUT]"
        echo "minishell status : $MINI_STATUS"
        echo "bash status      : $BASH_STATUS"
    fi
	echo
done
